export const initialValues = {
  vendor_id: '11798',
  name: 'fd',
  brand_id: '103',
  condition_id: '292',
  categories: [85],
  description: 'fd',
  enabled: 1,
  memberships: [],
  shipping_to_zones: [{ id: 1, price: '0.03' }],
  tax_exempt: 0,
  price: '342',
  sale_price_type: '$',
  arrival_date: '2022-07-20',
  inventory_tracking: 0,
  quantity: '32',
  sku: '1658307567233',
  participate_sale: 0,
  sale_price: '',
  og_tags_type: '0',
  og_tags: '',
  meta_desc_type: 'A',
  meta_description: '',
  meta_keywords: '',
  product_page_title: '',
  facebook_marketing_enabled: 0,
  google_feed_enabled: 0,
  imagesOrder: ['2021-10-26 (1).png'],
  deleted_images: [],
}
