export const initialValues = {
  vendor_id: '',
  name: '',
  brand_id: '',
  condition_id: '292',
  categories: [85],
  description: '',
  enabled: 1,
  memberships: [],
  shipping_to_zones: [{ id: 1, price: '0.03' }],
  tax_exempt: 0,
  price: '',
  sale_price_type: '$',
  arrival_date: '2022-07-20',
  inventory_tracking: 0,
  quantity: '32',
  sku: '',
  participate_sale: 0,
  sale_price: '',
  og_tags_type: '0',
  og_tags: '',
  meta_desc_type: 'A',
  meta_description: '',
  meta_keywords: '',
  product_page_title: '',
  facebook_marketing_enabled: 0,
  google_feed_enabled: 0,
  imagesOrder: [],
  deleted_images: [],
}
